version: "3"
services:
  db:
    build:
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
      context: .
      dockerfile: ./db/Dockerfile
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    restart: "on-failure"
    environment:
      MYSQL_DATABASE: dataconv
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
  back:
    build: .
    entrypoint: "python manage.py"
    command: "runserver 0.0.0.0:8000"
    volumes:
      - ".:/code"
    ports:
      - "8000:8000"
    depends_on:
      - db
  # front:
  #   image: node
  #   command: bash -c "npm install && npm run serve"
  #   volumes:
  #     - ./env:/app/.env
  #     - ./frontend:/app
  #   working_dir: /app
  #   restart: on-failure
  #   ports:
  #     - "8080:8080"
